

let animes = ["Naruto", "One Piece", "Attack on Titan", "Death Note", "Fullmetal Alchemist: Brotherhood", "My Hero Academia", "Dragon Ball Z", "Hunter x Hunter", "Demon Slayer", "Sword Art Online", "Neon Genesis Evangelion", "Steins;Gate", "Cowboy Bebop", "One Punch Man", "Tokyo Ghoul", "Bleach", "Fairy Tail", "JoJo's Bizarre Adventure", "Black Clover", "Re:Zero", "Haikyuu"]

let esportes = ["Futebol", "Basquetebol", "Tenis", "Golfe", "Criquete", "Rugby", "Hoquei no Gelo", "Voleibol", "Atletismo", "Natacao", "Tenis de Mesa", "Badminton", "Surfe", "Ciclismo", "Boxe", "Esqui", "Mergulho", "Canoagem", "Ginastica", "Escalada"]

let animais = ["Leao", "Elefante", "Tigre", "Girafa", "Zebra", "Urso-polar", "Orca", "Pinguim", "Rinoceronte", "Gorila", "Leopardo", "Panda Vermelho", "Baleia Jubarte", "Tubarao", "Canguru", "Papagaio", "Polvo", "Cavalo", "Cachorro", "Gato", "Golfinho", "Aguia-careca", "Esquilo", "Formiga", "Cobra", "Coruja", "Sapo", "Peixe-palhaço", "Morcego", "Beija-flor", "Cavalo-marinho", "Tartaruga", "Panda Gigante", "Coala", "Morsa", "Puma", "Caracol", "Lontra", "Ouriço", "Camelo", "Texugo", "Lagosta", "Gaviao", "Toupeira", "Vespa", "Iguana", "Puma", "Alce"]

let intrumentos = ["Violino", "Violoncelo", "Viola", "Contrabaixo", "Piano", "Guitarra", "Baixo eletrico", "Bateria", "Flauta", "Saxofone", "Trompete", "Trombone", "Clarinete", "Fagote", "Harpa", "Orgao", "Acordeao", "Violao", "Harmonica", "Xilofone", "Marimba", "Tamborim", "Bandolim", "Cavaquinho", "Gaita de foles", "Harpicordio", "Koto", "Sitar", "Citara", "Oud", "Djembe", "Didgeridoo", "Banjo", "Tuba", "Pandeireta", "Maracas", "Timpanos", "Foice", "Sinos de mao", "Mandolina", "Trompa", "Cuica", "Surdo", "Surdos de aro", "Flugelhorn"]

let cidades = ["Nova York", "Londres", "Paris", "Toquio", "Sydney", "Cidade do Mexico", "Istambul", "Rio de Janeiro", "Cairo", "Cidade do Cabo", "Roma", "Pequim", "Moscou", "Dubai", "Bangkok", "Los Angeles", "Toronto", "Buenos Aires", "Mumbai", "Barcelona", "Praga", "Hong Kong", "Amsterda", "Copenhague", "Veneza", "Atenas", "Estocolmo", "Edimburgo", "Viena", "Seul", "Marrakech", "Havana", "Auckland", "Ho Chi Minh", "Casablanca", "Helsinque", "Lisboa", "Doha", "Zurique", "Luxemburgo", "Reykjavik", "Kuala Lumpur", "Bruxelas", "Oslo"]

let comida = ["Pizza", "Sushi", "Hamburguer", "Massas", "Tacos", "Salmao grelhado", "Frango assado", "Lasanha", "Sopa de tomate", "Torta de maca", "Sanduiche de atum", "Curry de frango", "Camarao scampi", "Salada Caesar", "Banana split", "Tacos de peixe", "Risoto de cogumelos", "Bife de file mignon", "Sorvete de chocolate", "Tortellini", "Picanha", "Tiramisu", "Ceviche", "Macarrao com queijo", "Waffle", "Salmao defumado", "Churrasco", "Salada de frutas", "Batata frita", "Espaguete à carbonara", "Sopa de lentilha", "Sushi de salmao", "Torta de carne", "Ramen", "Chop suey", "Molho de churrasco", "Almondegas", "Frango frito", "Molho de queijo", "Mousse de chocolate", "Pudim de caramelo", "Bolinho de bacalhau", "Pao de alho", "Sorvete de baunilha", "Sopa de abobora", "Torta de frango", "Biscoitos de chocolate", "Rabanada"]